const fs = require('fs');
const path = require('path');

// Категории
const CATEGORIES = {
    'Кредитная история': '📋',
    'Одобрение и отказы': '✅',
    'Новостройка': '🏠',
    'Рефинансирование': '💰',
    'Программы ипотеки': '👨‍👩‍👧',
    'Страхование': '🛡️'
};

// Читаем все статьи
function getAllArticles() {
    const articlesDir = path.join(__dirname, '../../articles');
    const articles = [];

    if (!fs.existsSync(articlesDir)) {
        fs.mkdirSync(articlesDir, { recursive: true });
        return articles;
    }

    const files = fs.readdirSync(articlesDir).filter(f => f.endsWith('.json'));

    files.forEach(file => {
        try {
            const data = JSON.parse(fs.readFileSync(path.join(articlesDir, file), 'utf8'));
            articles.push({
                ...data,
                slug: file.replace('.json', '')
            });
        } catch (e) {
            console.error(`Error reading ${file}:`, e);
        }
    });

    return articles.sort((a, b) => new Date(b.date) - new Date(a.date));
}

// Генерируем главную страницу
function generateIndex(articles) {
    let articlesHtml = '';

    articles.forEach(article => {
        const categoryEmoji = CATEGORIES[article.category] || '📌';
        articlesHtml += `
        <article class="article-card">
            <div class="article-meta">
                <span>${categoryEmoji} ${article.category}</span>
                <span>${formatDate(article.date)}</span>
            </div>
            <h3><a href="/blog/${article.slug}.html">${article.title}</a></h3>
            <p class="excerpt">${article.hook}</p>
            <a href="/blog/${article.slug}.html" class="read-more">Читать статью →</a>
        </article>`;
    });

    const indexTemplate = fs.readFileSync(
        path.join(__dirname, '../templates/index.html'),
        'utf8'
    );

    // Генерируем категории
    let categoriesHtml = '';
    Object.entries(CATEGORIES).forEach(([cat, emoji]) => {
        const count = articles.filter(a => a.category === cat).length;
        if (count > 0) {
            categoriesHtml += `<a href="#${cat.toLowerCase().replace(/ /g, '-')}">${emoji} ${cat}</a>`;
        }
    });

    let html = indexTemplate
        .replace('<!-- Generated by build.js -->', articlesHtml)
        .replace('id="articles-list"', 'id="articles-list"');

    const categorySection = html.match(/<div class="categories" id="categories-list">(.*?)<\/div>/s);
    if (categorySection) {
        html = html.replace(categorySection[1], categoriesHtml);
    }

    fs.writeFileSync(path.join(__dirname, '../../docs/index.html'), html);
    console.log('✅ Generated index.html');
}

// Генерируем страницы статей
function generateArticlePages(articles) {
    const articleTemplate = `<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{TITLE} - Доступная ипотека</title>
    <meta name="description" content="{HOOK}">
    <meta name="keywords" content="ипотека, {CATEGORY}">
    <link rel="stylesheet" href="/blog/css/style.css">
</head>
<body>
    <!-- Header -->
    <header class="header">
        <div class="container">
            <div class="header-content">
                <div class="logo-section">
                    <div class="logo">D</div>
                    <div>
                        <h1>ДОСТУПНАЯ ИПОТЕКА</h1>
                        <p>ЭКСПЕРТНЫЙ БЛОГ</p>
                    </div>
                </div>
                <nav class="nav">
                    <a href="/blog/">Главная</a>
                    <a href="/blog/#категории">Категории</a>
                    <a href="/blog/#контакты">Контакты</a>
                </nav>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="main-layout">
            <!-- Article Content -->
            <main class="main-content">
                <article class="article-page">
                    <div class="article-meta">
                        <span>{CATEGORY_EMOJI} {CATEGORY}</span>
                        <span>{DATE}</span>
                    </div>
                    <h1>{TITLE}</h1>
                    <p class="hook">{HOOK}</p>
                    <div class="content">
                        {CONTENT}
                    </div>
                </article>
            </main>

            <!-- Sidebar -->
            <aside class="sidebar">
                <!-- Consultation -->
                <section class="sidebar-box consultation">
                    <h3>Нужна консультация?</h3>
                    <div class="author-photo">
                        <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4QCMRXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAEAAAAAQAABDigAwAEAAAAAQAABBoAAAAA/+0AOFBob3Rvc2hvcCAzLjAAOEJJTQQEAAAAAAAAOEJJTQQlAAAAAAAQ1B2M2Y4AsgTpgAmY7PhCfv/CABEI" alt="Елена Молокова">
                        <h4>Елена Молокова</h4>
                        <p>Консультант по ипотеке</p>
                    </div>
                    <p>Свяжитесь со мной, я разберу вашу ситуацию и помогу найти оптимальный вариант ипотеки.</p>
                    <div class="contact-links">
                        <a href="https://t.me/MolokovaBot">👉 Telegram</a>
                        <a href="https://max.ru/id263101640599_3_bot">👉 Max</a>
                        <a href="mailto:nev.fk@bk.ru">📧 Email</a>
                    </div>
                </section>

                <!-- Social Networks -->
                <section class="sidebar-box">
                    <h3>Мои соц. сети</h3>
                    <div class="social-links">
                        <a href="https://t.me/dostupnayaipoteka">📱 TG: dostupnayaipoteka</a>
                        <a href="https://t.me/Molokova_pro">📱 TG: Molokova_pro</a>
                        <a href="https://max.ru/dostupnayaipoteka">💬 MAX-канал</a>
                        <a href="https://vk.com/dostupnayaipoteka">▪️ ВКонтакте</a>
                        <a href="https://youtube.com/c/dostupnayaipoteka">📹 YouTube</a>
                        <a href="https://instagram.com/molokova_ipoteka">📸 Instagram</a>
                    </div>
                </section>
            </aside>
        </div>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <div class="footer-content">
                <div class="footer-logo">
                    <div class="logo-small">D</div>
                    <span>Доступная ипотека</span>
                </div>
                <div class="footer-copy">© 2026 Все права защищены.</div>
            </div>
        </div>
    </footer>
</body>
</html>`;

    articles.forEach(article => {
        const categoryEmoji = CATEGORIES[article.category] || '📌';

        let html = articleTemplate
            .replace('{TITLE}', article.title)
            .replace('{HOOK}', article.hook)
            .replace('{CATEGORY}', article.category)
            .replace('{CATEGORY_EMOJI}', categoryEmoji)
            .replace('{DATE}', formatDate(article.date))
            .replace('{CONTENT}', article.content);

        const outputPath = path.join(__dirname, `../../docs/${article.slug}.html`);
        fs.mkdirSync(path.dirname(outputPath), { recursive: true });
        fs.writeFileSync(outputPath, html);
        console.log(`✅ Generated ${article.slug}.html`);
    });
}

// Генерируем sitemap.xml
function generateSitemap(articles) {
    let urls = `  <url>
    <loc>https://dostupnayaipoteka.ru/blog/</loc>
    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>`;

    articles.forEach(article => {
        urls += `
  <url>
    <loc>https://dostupnayaipoteka.ru/blog/${article.slug}.html</loc>
    <lastmod>${article.date}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>`;
    });

    const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>`;

    fs.writeFileSync(path.join(__dirname, '../../docs/sitemap.xml'), sitemap);
    console.log('✅ Generated sitemap.xml');
}

// Генерируем robots.txt
function generateRobots() {
    const robots = `User-agent: *
Allow: /blog/
Disallow: /blog/admin/

Sitemap: https://dostupnayaipoteka.ru/blog/sitemap.xml`;

    fs.writeFileSync(path.join(__dirname, '../../docs/robots.txt'), robots);
    console.log('✅ Generated robots.txt');
}

// Копируем CSS
function copyCss() {
    const cssSource = path.join(__dirname, '../css/style.css');
    const cssDir = path.join(__dirname, '../../docs/css');
    const cssDest = path.join(cssDir, 'style.css');

    fs.mkdirSync(cssDir, { recursive: true });
    fs.copyFileSync(cssSource, cssDest);
    console.log('✅ Copied CSS');
}

// Форматируем дату
function formatDate(dateStr) {
    const date = new Date(dateStr);
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    return date.toLocaleDateString('ru-RU', options);
}

// Main
console.log('🚀 Building blog...');
const articles = getAllArticles();
console.log(`Found ${articles.length} articles`);

copyCss();
generateIndex(articles);
generateArticlePages(articles);
generateSitemap(articles);
generateRobots();

console.log('✅ Blog built successfully!');
